export const employeeSearchResults = [
    {
       "name": "John Doe",
       "title": "Business Operations, Services, and Support Analyst",
       "department": "Employment and Social Development Canada",
       "businessUnit": "Business Operations and Services: Division A",
       "email": "john.doe@hrsdc-rhdcc.gc.ca",
       "phone": "(999) 999 9999",
       "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
       "expansionPath": [10, 1, 0],
    },
    {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     },
     {
        "name": "John Doe",
        "title": "Business Operations, Services, and Support Analyst",
        "department": "Employment and Social Development Canada",
        "businessUnit": "Business Operations and Services: Division A",
        "email": "john.doe@hrsdc-rhdcc.gc.ca",
        "phone": "(999) 999 9999",
        "Address": "123 Fake Ave. Ottawa, Ontario (A1B 2C3)",
        "expansionPath": [10, 1, 0],
     }
]